name: 'mend scan'
description: 'this action is used to scan your repository using mend'
author: 'malikparvez'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  WS_APIKEY:
    description: 'Your input description here'
    required: true
  WS_USERKEY:
    description: 'Your input description here'
    required: true
  WS_PRODUCTNAME:
    description: 'Your input description here'
    required: true
  WS_PROJECTNAME:
    description: 'Your input description here'
    required: true

# Define your outputs here.
#outputs:
#  time:
#    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
